package main

import (
	"fmt"
	"gopkg.in/gomail.v2"
)

func main() {
	m := gomail.NewMessage()
	d := mailConfig(m)

	// 发送邮件
	if err := d.DialAndSend(m); err != nil {
		fmt.Printf("DialAndSend err %v:", err)
		panic(err)
	}
	fmt.Printf("send mail success.\n dial :%+v\n", d)
}

const (
	myEmail    = "79976@qq.com" // TODO fix it when use it
	otherEmail = "49573@qq.com" // TODO fix it when use it
	authCode   = "vrbprtlnubhpbbad"
)

func mailConfig(m *gomail.Message) *gomail.Dialer {
	//发送人
	m.SetHeader("From", myEmail)
	//接收人
	m.SetHeader("To", otherEmail)
	//抄送人
	m.SetAddressHeader("Cc", otherEmail, "小猪佩奇")
	//主题
	m.SetHeader("Subject", "小佩奇的一封信")
	//内容
	m.SetBody("text/html", getLocalHtml())
	//附件
	//m.Attach("./main.go")

	//拿到token，并进行连接,第4个参数是填授权码
	return gomail.NewDialer("smtp.qq.com", 587, myEmail, authCode)
}

func mailBody() string {
	return "<h1>新年快乐</h1>"
}

func getLocalHtml() string {
	return `<html>
<head>
    <meta charset="utf-8">
    <title>Awesome go-echarts</title>
    <script src="https://go-echarts.github.io/go-echarts-assets/assets/echarts.min.js"></script>
</head>

<body>
<div class="container">
    <div class="item" id="GQVBuooKBgLL" style="width:900px;height:500px;"></div>
</div>

<script type="text/javascript">
    "use strict";
    let goecharts_GQVBuooKBgLL = echarts.init(document.getElementById('GQVBuooKBgLL'), "white");
    let option_GQVBuooKBgLL = {"color":["#5470c6","#91cc75","#fac858","#ee6666","#73c0de","#3ba272","#fc8452","#9a60b4","#ea7ccc"],"legend":{"show":false},"series":[{"name":"Category A","type":"bar","waveAnimation":false,"renderLabelForZeroData":false,"selectedMode":false,"animation":false,"data":[{"value":42},{"value":60},{"value":51},{"value":140},{"value":75},{"value":224},{"value":202}]},{"name":"Category B","type":"bar","waveAnimation":false,"renderLabelForZeroData":false,"selectedMode":false,"animation":false,"data":[{"value":191},{"value":106},{"value":237},{"value":265},{"value":235},{"value":157},{"value":210}]}],"title":{"text":"My first bar chart generated by go-echarts","subtext":"It's extremely easy to use, right?"},"tooltip":{"show":false},"xAxis":[{"data":["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]}],"yAxis":[{}]};
    goecharts_GQVBuooKBgLL.setOption(option_GQVBuooKBgLL);
</script>

<style>
    .container {margin-top:30px; display: flex;justify-content: center;align-items: center;}
    .item {margin: auto;}
</style>
</body>
</html>`
}
